services:
  mongodb:
    image: mongo:6.0
    container_name: health-app-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: healthapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - health-app-network
  backend:
    image: ${DOCKER_HUB_USERNAME}/health-app-backend:latest
    container_name: health-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_CONNECTION_STRING}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
      - redis
    networks:
      - health-app-network
  frontend-web:
    image: ${DOCKER_HUB_USERNAME}/health-app-frontend-web:latest
    container_name: health-app-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://backend:5000/api
      VITE_SOCKET_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - health-app-network
  admin-dashboard:
    image: ${DOCKER_HUB_USERNAME}/health-app-admin-dashboard:latest
    container_name: health-app-admin
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      VITE_API_URL: http://backend:5000/api
    depends_on:
      - backend
    networks:
      - health-app-network
  # ... add redis, prometheus, grafana as needed
volumes:
  mongodb_data:
  redis_data:
networks:
  health-app-network:
    driver: bridge
