version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - health-app-network

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - health-app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis
    networks:
      - health-app-network

  frontend-web:
    build: 
      context: ./frontend-web
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - health-app-network

  admin-dashboard:
    build: 
      context: ./admin-dashboard
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - health-app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend-web
      - admin-dashboard
    networks:
      - health-app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  health-app-network:
    driver: bridge
