name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "http://production.example.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push
      # - name: Deploy to production server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.PRODUCTION_SERVER_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.PRODUCTION_SSH_KEY }}
      #     script: |
      #       cd /path/to/production/health-app
      #       docker-compose -f docker-compose.prod.yml pull
      #       docker-compose -f docker-compose.prod.yml up -d || (docker-compose -f docker-compose.prod.yml down && exit 1)
      # - name: Run smoke tests
      #   run: |
      #     curl -f http://${{ secrets.PRODUCTION_SERVER_HOST }}:5000/health
      - name: Notify team
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "deployments"
          text: "Production deployment ${{ job.status }} for health-app"
